/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edunova.view;

import edunova.controller.ObradaOperater;
import edunova.model.Operater;
import edunova.util.Aplikacija;
import java.awt.event.KeyEvent;

/**
 *
 * @author Feecho
 */
public class ProzorLogin extends javax.swing.JFrame {

    private ObradaOperater obrada;

    /**
     * Creates new form ProzorLogin
     */
    public ProzorLogin() {
        initComponents();
        obrada = new ObradaOperater();

        setTitle(Aplikacija.NAZIV_APP + " login");
    }

    private void autoriziraj() {
        lblPoruka.setText("");
        if (txtUsername.getText().isEmpty()) {
            lblPoruka.setText("Obavezan username");
            return;
        }
        if (pswLozinka.getPassword().length == 0) {
            lblPoruka.setText("Obavezna lozinka");
            return;
        }

        Operater o = obrada.Autoriziraj(txtUsername.getText(), pswLozinka.getPassword());
        if (o == null) {
            lblPoruka.setText("Neispravna kombinacija email i lozinka");
            return;
        }
        
        Aplikacija.OPERATER=o.getUsername();
        new ProzorIzbornik().setVisible(true);
        dispose();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pswLozinka = new javax.swing.JPasswordField();
        btnAutorizitaj = new javax.swing.JButton();
        lblPoruka = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Username");

        txtUsername.setText("Admin");
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        txtUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUsernameKeyPressed(evt);
            }
        });

        jLabel2.setText("Lozinka");

        pswLozinka.setText("edunova");
        pswLozinka.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pswLozinkaKeyPressed(evt);
            }
        });

        btnAutorizitaj.setText("Autoriziraj");
        btnAutorizitaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutorizitajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUsername)
                    .addComponent(pswLozinka)
                    .addComponent(btnAutorizitaj, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lblPoruka, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(pswLozinka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(btnAutorizitaj)
                .addGap(18, 18, 18)
                .addComponent(lblPoruka, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void btnAutorizitajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutorizitajActionPerformed
        autoriziraj();
    }//GEN-LAST:event_btnAutorizitajActionPerformed

    private void txtUsernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsernameKeyPressed
        lblPoruka.setText("");
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txtUsername.getText().isEmpty()) {
                lblPoruka.setText("Obavezan username");
                return;
            }
            if (pswLozinka.getPassword().length == 0) {
                pswLozinka.requestFocus();
                lblPoruka.setText("Obavezna lozinka");
                return;
            }
            autoriziraj();

        }

    }//GEN-LAST:event_txtUsernameKeyPressed

    private void pswLozinkaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pswLozinkaKeyPressed
        lblPoruka.setText("");
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            if (pswLozinka.getPassword().length == 0) {
                lblPoruka.setText("Obavezna lozinka");
                return;
            }
            if (txtUsername.getText().isEmpty()) {
                lblPoruka.setText("Obavezan username");
                txtUsername.requestFocus();
                return;
            }
            autoriziraj();
        }


    }//GEN-LAST:event_pswLozinkaKeyPressed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAutorizitaj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblPoruka;
    private javax.swing.JPasswordField pswLozinka;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
