/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edunova.view;

import com.github.lgooddatepicker.components.DatePickerSettings;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import edunova.controller.ObradaRacun;
import edunova.model.Entitet;
import edunova.model.Racun;
import edunova.model.StavkaRacuna;
import edunova.util.Aplikacija;

import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;


/**
 *
 * @author Feecho
 */
public class ProzorPDF extends javax.swing.JFrame {

    /**
     * Creates new form ProzorPDF
     */
    private ObradaRacun obrada;

    public ProzorPDF() {
        initComponents();
        obrada = new ObradaRacun();
        buttonGroup1.add(btnPoBlagajniku);
        buttonGroup1.add(btnPoBrRacuna);
        buttonGroup1.add(btnPoDatumu);
        DatePickerSettings dps
                = new DatePickerSettings(new Locale.Builder().setLanguage("hr").setRegion("HR").build());

        ArrayList<DateTimeFormatter> formatsForParsing = new ArrayList<>();
        formatsForParsing.add(DateTimeFormatter.ofPattern("dd.MM.yyyy"));
        dps.setFormatForDatesCommonEra("dd.MM.YYYY");
        dps.setFormatsForParsing(formatsForParsing);

        dps.setTranslationClear("Očisti");
        dps.setTranslationToday("Danas");

        dtpDatum.setSettings(dps);
        ucitaj();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jFrame1 = new javax.swing.JFrame();
        btnZatvori = new javax.swing.JButton();
        dtpDatum = new com.github.lgooddatepicker.components.DatePicker();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstPodaci = new javax.swing.JList<>();
        txtTrazilica = new javax.swing.JTextField();
        btnDatePicker = new javax.swing.JButton();
        btnTrazilica = new javax.swing.JButton();
        btnPoBlagajniku = new javax.swing.JRadioButton();
        btnPoBrRacuna = new javax.swing.JRadioButton();
        btnPoDatumu = new javax.swing.JRadioButton();
        btnIspisi = new javax.swing.JButton();

        jFrame1.setSize(new java.awt.Dimension(160, 120));
        jFrame1.setType(java.awt.Window.Type.POPUP);

        btnZatvori.setText("Postavi Datum");
        btnZatvori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZatvoriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnZatvori)
                    .addComponent(dtpDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(dtpDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnZatvori)
                .addGap(86, 86, 86))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lstPodaci.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstPodaci.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstPodaciValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstPodaci);

        txtTrazilica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTrazilicaActionPerformed(evt);
            }
        });

        btnDatePicker.setText("🗓");
        btnDatePicker.setMaximumSize(new java.awt.Dimension(30, 30));
        btnDatePicker.setMinimumSize(new java.awt.Dimension(20, 20));
        btnDatePicker.setPreferredSize(new java.awt.Dimension(20, 20));
        btnDatePicker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatePickerActionPerformed(evt);
            }
        });

        btnTrazilica.setText("Trazi");
        btnTrazilica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrazilicaActionPerformed(evt);
            }
        });

        btnPoBlagajniku.setText("Trazi po blagajniku");
        btnPoBlagajniku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPoBlagajnikuActionPerformed(evt);
            }
        });

        btnPoBrRacuna.setText("Trazi po broju racuna");
        btnPoBrRacuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPoBrRacunaActionPerformed(evt);
            }
        });

        btnPoDatumu.setText("Trazi po datumu");
        btnPoDatumu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPoDatumuActionPerformed(evt);
            }
        });

        btnIspisi.setText("Ispisi");
        btnIspisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIspisiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtTrazilica, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTrazilica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPoBlagajniku)
                            .addComponent(btnPoBrRacuna)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnIspisi)
                            .addComponent(btnPoDatumu))))
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTrazilica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTrazilica)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnPoBlagajniku, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPoBrRacuna)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPoDatumu)
                        .addGap(29, 29, 29)
                        .addComponent(btnIspisi)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lstPodaciValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstPodaciValueChanged
        if (evt.getValueIsAdjusting()) {
            return;
        }
        if (lstPodaci.getSelectedValue() == null) {
            return;
        }

        obrada.setEntitet(lstPodaci.getSelectedValue());


    }//GEN-LAST:event_lstPodaciValueChanged

    private void txtTrazilicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTrazilicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTrazilicaActionPerformed

    private void btnDatePickerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatePickerActionPerformed
        jFrame1.setLocationRelativeTo(null);
        jFrame1.setVisible(true);
        btnPoDatumu.doClick();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDatePickerActionPerformed

    private void btnTrazilicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrazilicaActionPerformed
        ucitaj();

    }//GEN-LAST:event_btnTrazilicaActionPerformed

    private void btnPoBlagajnikuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPoBlagajnikuActionPerformed
        txtTrazilica.setEditable(true);
        txtTrazilica.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPoBlagajnikuActionPerformed

    private void btnPoBrRacunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPoBrRacunaActionPerformed
        txtTrazilica.setEditable(true);
        txtTrazilica.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPoBrRacunaActionPerformed

    private void btnPoDatumuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPoDatumuActionPerformed
        txtTrazilica.setEditable(false);
        txtTrazilica.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPoDatumuActionPerformed

    private void btnZatvoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZatvoriActionPerformed

        txtTrazilica.setText(dtpDatum.getText());
        btnTrazilica.doClick();
        jFrame1.dispose();
    }//GEN-LAST:event_btnZatvoriActionPerformed

    private void btnIspisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIspisiActionPerformed
        if (lstPodaci.getSelectedValue() == null) {
            JOptionPane.showMessageDialog(rootPane, "Prvo odaberite racun!");
            return;
        }
        Racun r = lstPodaci.getSelectedValue();
        Document document = new Document() {};
        try {
            PdfWriter.getInstance(document, new FileOutputStream(r.getBrojRacuna()+".pdf"));
        } catch (FileNotFoundException | DocumentException ex) {
            Logger.getLogger(ProzorPDF.class.getName()).log(Level.SEVERE, null, ex);
        }

        document.open();
        Font font = FontFactory.getFont(FontFactory.COURIER, 16, BaseColor.BLACK);
//        Chunk chunk = new Chunk("Racun broj: "+r.getBrojRacuna(), font);
//        Chunk chunk2 = new Chunk(r.getBlagajnik().getUsername(),font);
        
        try {
            document.add(new Paragraph("Blagajnik: "+r.getBlagajnik().getUsername(),font));
            document.add(new Paragraph("Racun broj: "+r.getBrojRacuna(), font));
            document.add(new Paragraph("Datum izdatka: "+Aplikacija.df.format(r.getDatum()), font));
            document.add(new Paragraph("________________________________________"));
            for(StavkaRacuna stavka : r.getStavkeRacuna()){
            document.add(new Paragraph(stavka.getProizvod().getImeProizvoda()+" "+stavka.getCijenaProizvoda()+"kn "+stavka.getKolicina(), font));
            }
            document.add(new Paragraph("________________________________________"));
            document.add(new Paragraph("Ukupno za platiti: "+r.getZaPlatiti()+"kn",font));
        } catch (DocumentException ex) {
            Logger.getLogger(ProzorPDF.class.getName()).log(Level.SEVERE, null, ex);
        }
        document.close();
    }//GEN-LAST:event_btnIspisiActionPerformed

    private void ucitaj() {
        DefaultListModel<Racun> m
                = new DefaultListModel<>();
        if (!txtTrazilica.getText().isBlank()) {
            m.addAll(obrada.read(txtTrazilica.getText(), getSelectedButtonIndex(buttonGroup1)));
        } else {
            m.addAll(obrada.read());
        }

        lstPodaci.setModel(m);
        lstPodaci.repaint();
    }

    private int getSelectedButtonIndex(ButtonGroup buttonGroup) {
        int index = 0;
        for (Enumeration<AbstractButton> buttons = buttonGroup.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();

            if (button.isSelected()) {
                return index;
            }
            index++;
        }

        return 0;
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDatePicker;
    private javax.swing.JButton btnIspisi;
    private javax.swing.JRadioButton btnPoBlagajniku;
    private javax.swing.JRadioButton btnPoBrRacuna;
    private javax.swing.JRadioButton btnPoDatumu;
    private javax.swing.JButton btnTrazilica;
    private javax.swing.JButton btnZatvori;
    private javax.swing.ButtonGroup buttonGroup1;
    private com.github.lgooddatepicker.components.DatePicker dtpDatum;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<Racun> lstPodaci;
    private javax.swing.JTextField txtTrazilica;
    // End of variables declaration//GEN-END:variables
}
